updated path in notebook to 2023 aqcuired data
geoscixyz/gpgLabs pull request #137
Opened 2023-09-22 18:19 UTC by JKutt

A quick PR to update the path to magnetic data file acquired 2023 for EOAS 350

2023-09-22 18:20 UTC, JKutt commented
@santisoler , it looks like some of the notebook parameters changed when I saved to older versions of a few things. Will this matter. Should I maybe just edit the straight text?

2023-09-22 18:29 UTC, santisoler commented
Thanks for this PR @JKutt! I suspect those values will be overwritten when the students open the notebook with the kernels in the JupyterHub. But if we want to be sure we are not going to break anything, we can totally restore the previous changes on those two lines. I can do it, no worries.

On a side note, I would merge this PR after the file is uploaded.

2023-09-22 18:29 UTC, santisoler requested changes
A few suggestions to restore the original kernel parameters in the notebook

2023-09-22 18:29 UTC, santisoler commented on notebooks/mag/Mag_FitProfile.ipynb
> +   "display_name": "Python 3",
```suggestion
   "display_name": "Python 3 (ipykernel)",
```

2023-09-22 18:29 UTC, santisoler commented on notebooks/mag/Mag_FitProfile.ipynb
> +   "version": "3.8.8"
```suggestion
   "version": "3.10.4"
```

2023-09-23 00:23 UTC, santisoler approved these changes

2023-09-23 00:26 UTC, merged